[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "research"
    name = "Research"
    url = "/research"
    weight = 2

#[[main]]
    #identifier = "team"
    #name = "Team"
    #url = "/team"
    #weight = 3


#[[main]]
    #identifier = "get_involved"
    #name = "Get Involved"
    #url = "/get-involved"
    #weight = 4

[[main]] 
    identifier = "aisc"
    name = "AISC"
    url = "https://unsearch-ai.notion.site/AISC-2024-Research-Proposal-5adbd5918fe443c491a0a5b4252113fc?pvs=4"
    weight = 5

#[[main]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories"
#    weight = 3

#[[main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags"
#    weight = 4

#[[main]]
#    identifier = "donate"
#    name = "Donate"
#    url = "https://ko-fi.com/nixentric"
#    weight = 5


# Social Media Configuration

#[[social]]
#    identifier = "twitter"
#    name = "Twitter"
#    url = "#"
#    weight = 1

#[[social]]
#    identifier = "instagram"
#    name = "Instagram"
#    url = "#"
#    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/understanding-search"
    weight = 3