# Homepage Config
isSinglePage = true

# Meta Config
description = "Hello"

# Header Configuration
avatar = "img/logo.png"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

 # giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]
    enable = true
    repo = "understanding-search/another_site"
    repoId = "R_kgDOKpwuvQ"
    category = "Discussion"
    categoryId = "DIC_kwDOKpwuvc4CatmI"
    mapping = "title"  # comment value is the default value
    strict = 0
    reactionsEnabled = 1
    emitMetadata = 0
    inputPosition = "bottom"
    theme = "preferred_color_scheme"
    lang = "en"
    lazyLoading = true